### ISSUE TITLE
Failed because Ruby 2.3 is required

### ISSUE THREAD

**Issue by llbbl** [mrlesmithjr/ansible-jekyll#1]
> failed: [] (item=github-pages) => {"changed": false, "cmd": "/usr/bin/gem install --no-user-install --no-document github-pages", "item": "github-pages", "msg": "ERROR:  Error installing github-pages:\n\tjekyll-seo-tag requires Ruby version >= 2.3.0.", "rc": 1, "stderr": "ERROR:  Error installing github-pages:\n\tjekyll-seo-tag requires Ruby version >= 2.3.0.\n", "stderr_lines": ["ERROR:  Error installing github-pages:", "\tjekyll-seo-tag requires Ruby version >= 2.3.0."], "stdout": "Successfully installed unicode-display_width-1.4.0\nSuccessfully installed terminal-table-1.8.0\nSuccessfully installed rouge-2.2.1\nSuccessfully installed kramdown-1.16.2\nSuccessfully installed public_suffix-2.0.5\nSuccessfully installed jekyll-3.7.3\n", "stdout_lines": ["Successfully installed unicode-display_width-1.4.0", "Successfully installed terminal-table-1.8.0", "Successfully installed rouge-2.2.1", "Successfully installed kramdown-1.16.2", "Successfully installed public_suffix-2.0.5", "Successfully installed jekyll-3.7.3"]}

**Comment by mrlesmithjr** [comment]
@llbbl Thanks for reporting this. I will have to take a look into this as soon as I get some time to do so.

**Comment by llbbl** [comment]
@mrlesmithjr sure yea np. I ended up just creating my own role. 

```
- name: Installing base Packages
  apt: name=ruby-full state=present

- name: Install Bundler
  gem:
    name: bundler
    user_install: no

- name: Install Jekyll
  gem:
    name: jekyll
    user_install: no
```
